#!/bin/php -q
<?php
/**
 * @ide         PhpStorm.
 * @author:     Pnsme
 * @datetime:   2017-7-7 23:04
 * @version:    0.1
 * @description:   入口
 */

include_once 'updater.php';
$updater = updater::getInstance();
$options = $updater->get_options();
$input = getopt($options['short'], $options['long']);
$updater->handle($input);


